// Code generated by entc, DO NOT EDIT.

package mixer

const (
	// Label holds the string label denoting the mixer type in the database.
	Label = "mixer"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the mixer in the database.
	Table = "mixers"
)

// Columns holds all SQL columns for mixer fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
