// Code generated by entc, DO NOT EDIT.

package ent

import (
	"boschtail/ent/mixerconfig"
	"boschtail/ent/predicate"
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MixerConfigQuery is the builder for querying MixerConfig entities.
type MixerConfigQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.MixerConfig
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MixerConfigQuery builder.
func (mcq *MixerConfigQuery) Where(ps ...predicate.MixerConfig) *MixerConfigQuery {
	mcq.predicates = append(mcq.predicates, ps...)
	return mcq
}

// Limit adds a limit step to the query.
func (mcq *MixerConfigQuery) Limit(limit int) *MixerConfigQuery {
	mcq.limit = &limit
	return mcq
}

// Offset adds an offset step to the query.
func (mcq *MixerConfigQuery) Offset(offset int) *MixerConfigQuery {
	mcq.offset = &offset
	return mcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mcq *MixerConfigQuery) Unique(unique bool) *MixerConfigQuery {
	mcq.unique = &unique
	return mcq
}

// Order adds an order step to the query.
func (mcq *MixerConfigQuery) Order(o ...OrderFunc) *MixerConfigQuery {
	mcq.order = append(mcq.order, o...)
	return mcq
}

// First returns the first MixerConfig entity from the query.
// Returns a *NotFoundError when no MixerConfig was found.
func (mcq *MixerConfigQuery) First(ctx context.Context) (*MixerConfig, error) {
	nodes, err := mcq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{mixerconfig.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mcq *MixerConfigQuery) FirstX(ctx context.Context) *MixerConfig {
	node, err := mcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MixerConfig ID from the query.
// Returns a *NotFoundError when no MixerConfig ID was found.
func (mcq *MixerConfigQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mcq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{mixerconfig.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mcq *MixerConfigQuery) FirstIDX(ctx context.Context) int {
	id, err := mcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MixerConfig entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MixerConfig entity is found.
// Returns a *NotFoundError when no MixerConfig entities are found.
func (mcq *MixerConfigQuery) Only(ctx context.Context) (*MixerConfig, error) {
	nodes, err := mcq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{mixerconfig.Label}
	default:
		return nil, &NotSingularError{mixerconfig.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mcq *MixerConfigQuery) OnlyX(ctx context.Context) *MixerConfig {
	node, err := mcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MixerConfig ID in the query.
// Returns a *NotSingularError when more than one MixerConfig ID is found.
// Returns a *NotFoundError when no entities are found.
func (mcq *MixerConfigQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mcq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{mixerconfig.Label}
	default:
		err = &NotSingularError{mixerconfig.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mcq *MixerConfigQuery) OnlyIDX(ctx context.Context) int {
	id, err := mcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MixerConfigs.
func (mcq *MixerConfigQuery) All(ctx context.Context) ([]*MixerConfig, error) {
	if err := mcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return mcq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (mcq *MixerConfigQuery) AllX(ctx context.Context) []*MixerConfig {
	nodes, err := mcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MixerConfig IDs.
func (mcq *MixerConfigQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := mcq.Select(mixerconfig.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mcq *MixerConfigQuery) IDsX(ctx context.Context) []int {
	ids, err := mcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mcq *MixerConfigQuery) Count(ctx context.Context) (int, error) {
	if err := mcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return mcq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (mcq *MixerConfigQuery) CountX(ctx context.Context) int {
	count, err := mcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mcq *MixerConfigQuery) Exist(ctx context.Context) (bool, error) {
	if err := mcq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return mcq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (mcq *MixerConfigQuery) ExistX(ctx context.Context) bool {
	exist, err := mcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MixerConfigQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mcq *MixerConfigQuery) Clone() *MixerConfigQuery {
	if mcq == nil {
		return nil
	}
	return &MixerConfigQuery{
		config:     mcq.config,
		limit:      mcq.limit,
		offset:     mcq.offset,
		order:      append([]OrderFunc{}, mcq.order...),
		predicates: append([]predicate.MixerConfig{}, mcq.predicates...),
		// clone intermediate query.
		sql:    mcq.sql.Clone(),
		path:   mcq.path,
		unique: mcq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (mcq *MixerConfigQuery) GroupBy(field string, fields ...string) *MixerConfigGroupBy {
	group := &MixerConfigGroupBy{config: mcq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := mcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return mcq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (mcq *MixerConfigQuery) Select(fields ...string) *MixerConfigSelect {
	mcq.fields = append(mcq.fields, fields...)
	return &MixerConfigSelect{MixerConfigQuery: mcq}
}

func (mcq *MixerConfigQuery) prepareQuery(ctx context.Context) error {
	for _, f := range mcq.fields {
		if !mixerconfig.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mcq.path != nil {
		prev, err := mcq.path(ctx)
		if err != nil {
			return err
		}
		mcq.sql = prev
	}
	return nil
}

func (mcq *MixerConfigQuery) sqlAll(ctx context.Context) ([]*MixerConfig, error) {
	var (
		nodes = []*MixerConfig{}
		_spec = mcq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &MixerConfig{config: mcq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, mcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (mcq *MixerConfigQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mcq.querySpec()
	_spec.Node.Columns = mcq.fields
	if len(mcq.fields) > 0 {
		_spec.Unique = mcq.unique != nil && *mcq.unique
	}
	return sqlgraph.CountNodes(ctx, mcq.driver, _spec)
}

func (mcq *MixerConfigQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := mcq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (mcq *MixerConfigQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   mixerconfig.Table,
			Columns: mixerconfig.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: mixerconfig.FieldID,
			},
		},
		From:   mcq.sql,
		Unique: true,
	}
	if unique := mcq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := mcq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mixerconfig.FieldID)
		for i := range fields {
			if fields[i] != mixerconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mcq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mcq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mcq *MixerConfigQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mcq.driver.Dialect())
	t1 := builder.Table(mixerconfig.Table)
	columns := mcq.fields
	if len(columns) == 0 {
		columns = mixerconfig.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mcq.sql != nil {
		selector = mcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mcq.unique != nil && *mcq.unique {
		selector.Distinct()
	}
	for _, p := range mcq.predicates {
		p(selector)
	}
	for _, p := range mcq.order {
		p(selector)
	}
	if offset := mcq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mcq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MixerConfigGroupBy is the group-by builder for MixerConfig entities.
type MixerConfigGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mcgb *MixerConfigGroupBy) Aggregate(fns ...AggregateFunc) *MixerConfigGroupBy {
	mcgb.fns = append(mcgb.fns, fns...)
	return mcgb
}

// Scan applies the group-by query and scans the result into the given value.
func (mcgb *MixerConfigGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := mcgb.path(ctx)
	if err != nil {
		return err
	}
	mcgb.sql = query
	return mcgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (mcgb *MixerConfigGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := mcgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (mcgb *MixerConfigGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(mcgb.fields) > 1 {
		return nil, errors.New("ent: MixerConfigGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := mcgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (mcgb *MixerConfigGroupBy) StringsX(ctx context.Context) []string {
	v, err := mcgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (mcgb *MixerConfigGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = mcgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mixerconfig.Label}
	default:
		err = fmt.Errorf("ent: MixerConfigGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (mcgb *MixerConfigGroupBy) StringX(ctx context.Context) string {
	v, err := mcgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (mcgb *MixerConfigGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(mcgb.fields) > 1 {
		return nil, errors.New("ent: MixerConfigGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := mcgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (mcgb *MixerConfigGroupBy) IntsX(ctx context.Context) []int {
	v, err := mcgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (mcgb *MixerConfigGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = mcgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mixerconfig.Label}
	default:
		err = fmt.Errorf("ent: MixerConfigGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (mcgb *MixerConfigGroupBy) IntX(ctx context.Context) int {
	v, err := mcgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (mcgb *MixerConfigGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(mcgb.fields) > 1 {
		return nil, errors.New("ent: MixerConfigGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := mcgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (mcgb *MixerConfigGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := mcgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (mcgb *MixerConfigGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = mcgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mixerconfig.Label}
	default:
		err = fmt.Errorf("ent: MixerConfigGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (mcgb *MixerConfigGroupBy) Float64X(ctx context.Context) float64 {
	v, err := mcgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (mcgb *MixerConfigGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(mcgb.fields) > 1 {
		return nil, errors.New("ent: MixerConfigGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := mcgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (mcgb *MixerConfigGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := mcgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (mcgb *MixerConfigGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = mcgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mixerconfig.Label}
	default:
		err = fmt.Errorf("ent: MixerConfigGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (mcgb *MixerConfigGroupBy) BoolX(ctx context.Context) bool {
	v, err := mcgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (mcgb *MixerConfigGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range mcgb.fields {
		if !mixerconfig.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := mcgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mcgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (mcgb *MixerConfigGroupBy) sqlQuery() *sql.Selector {
	selector := mcgb.sql.Select()
	aggregation := make([]string, 0, len(mcgb.fns))
	for _, fn := range mcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(mcgb.fields)+len(mcgb.fns))
		for _, f := range mcgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(mcgb.fields...)...)
}

// MixerConfigSelect is the builder for selecting fields of MixerConfig entities.
type MixerConfigSelect struct {
	*MixerConfigQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (mcs *MixerConfigSelect) Scan(ctx context.Context, v interface{}) error {
	if err := mcs.prepareQuery(ctx); err != nil {
		return err
	}
	mcs.sql = mcs.MixerConfigQuery.sqlQuery(ctx)
	return mcs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (mcs *MixerConfigSelect) ScanX(ctx context.Context, v interface{}) {
	if err := mcs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (mcs *MixerConfigSelect) Strings(ctx context.Context) ([]string, error) {
	if len(mcs.fields) > 1 {
		return nil, errors.New("ent: MixerConfigSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := mcs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (mcs *MixerConfigSelect) StringsX(ctx context.Context) []string {
	v, err := mcs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (mcs *MixerConfigSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = mcs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mixerconfig.Label}
	default:
		err = fmt.Errorf("ent: MixerConfigSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (mcs *MixerConfigSelect) StringX(ctx context.Context) string {
	v, err := mcs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (mcs *MixerConfigSelect) Ints(ctx context.Context) ([]int, error) {
	if len(mcs.fields) > 1 {
		return nil, errors.New("ent: MixerConfigSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := mcs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (mcs *MixerConfigSelect) IntsX(ctx context.Context) []int {
	v, err := mcs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (mcs *MixerConfigSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = mcs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mixerconfig.Label}
	default:
		err = fmt.Errorf("ent: MixerConfigSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (mcs *MixerConfigSelect) IntX(ctx context.Context) int {
	v, err := mcs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (mcs *MixerConfigSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(mcs.fields) > 1 {
		return nil, errors.New("ent: MixerConfigSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := mcs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (mcs *MixerConfigSelect) Float64sX(ctx context.Context) []float64 {
	v, err := mcs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (mcs *MixerConfigSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = mcs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mixerconfig.Label}
	default:
		err = fmt.Errorf("ent: MixerConfigSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (mcs *MixerConfigSelect) Float64X(ctx context.Context) float64 {
	v, err := mcs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (mcs *MixerConfigSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(mcs.fields) > 1 {
		return nil, errors.New("ent: MixerConfigSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := mcs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (mcs *MixerConfigSelect) BoolsX(ctx context.Context) []bool {
	v, err := mcs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (mcs *MixerConfigSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = mcs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{mixerconfig.Label}
	default:
		err = fmt.Errorf("ent: MixerConfigSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (mcs *MixerConfigSelect) BoolX(ctx context.Context) bool {
	v, err := mcs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (mcs *MixerConfigSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := mcs.sql.Query()
	if err := mcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
