// Code generated by entc, DO NOT EDIT.

package ent

import (
	"boschtail/ent/mixerconfig"
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// MixerConfig is the model entity for the MixerConfig schema.
type MixerConfig struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MixerConfig) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case mixerconfig.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type MixerConfig", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MixerConfig fields.
func (mc *MixerConfig) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mixerconfig.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			mc.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this MixerConfig.
// Note that you need to call MixerConfig.Unwrap() before calling this method if this MixerConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (mc *MixerConfig) Update() *MixerConfigUpdateOne {
	return (&MixerConfigClient{config: mc.config}).UpdateOne(mc)
}

// Unwrap unwraps the MixerConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (mc *MixerConfig) Unwrap() *MixerConfig {
	tx, ok := mc.config.driver.(*txDriver)
	if !ok {
		panic("ent: MixerConfig is not a transactional entity")
	}
	mc.config.driver = tx.drv
	return mc
}

// String implements the fmt.Stringer.
func (mc *MixerConfig) String() string {
	var builder strings.Builder
	builder.WriteString("MixerConfig(")
	builder.WriteString(fmt.Sprintf("id=%v", mc.ID))
	builder.WriteByte(')')
	return builder.String()
}

// MixerConfigs is a parsable slice of MixerConfig.
type MixerConfigs []*MixerConfig

func (mc MixerConfigs) config(cfg config) {
	for _i := range mc {
		mc[_i].config = cfg
	}
}
