// Code generated by entc, DO NOT EDIT.

package ent

import (
	"boschtail/ent/recipeingredient"
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// RecipeIngredient is the model entity for the RecipeIngredient schema.
type RecipeIngredient struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RecipeIngredient) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case recipeingredient.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type RecipeIngredient", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RecipeIngredient fields.
func (ri *RecipeIngredient) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case recipeingredient.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ri.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this RecipeIngredient.
// Note that you need to call RecipeIngredient.Unwrap() before calling this method if this RecipeIngredient
// was returned from a transaction, and the transaction was committed or rolled back.
func (ri *RecipeIngredient) Update() *RecipeIngredientUpdateOne {
	return (&RecipeIngredientClient{config: ri.config}).UpdateOne(ri)
}

// Unwrap unwraps the RecipeIngredient entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ri *RecipeIngredient) Unwrap() *RecipeIngredient {
	tx, ok := ri.config.driver.(*txDriver)
	if !ok {
		panic("ent: RecipeIngredient is not a transactional entity")
	}
	ri.config.driver = tx.drv
	return ri
}

// String implements the fmt.Stringer.
func (ri *RecipeIngredient) String() string {
	var builder strings.Builder
	builder.WriteString("RecipeIngredient(")
	builder.WriteString(fmt.Sprintf("id=%v", ri.ID))
	builder.WriteByte(')')
	return builder.String()
}

// RecipeIngredients is a parsable slice of RecipeIngredient.
type RecipeIngredients []*RecipeIngredient

func (ri RecipeIngredients) config(cfg config) {
	for _i := range ri {
		ri[_i].config = cfg
	}
}
