// Code generated by entc, DO NOT EDIT.

package mixerconfig

const (
	// Label holds the string label denoting the mixerconfig type in the database.
	Label = "mixer_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the mixerconfig in the database.
	Table = "mixer_configs"
)

// Columns holds all SQL columns for mixerconfig fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
